### ISSUE TITLE
Async error at startup

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.mielecloudservice#107]
Hab heute ein git-Update gemacht und bekomme seitdem die folgenden Fehlermeldung als Version wird 4.01 angegeben.

  |   |   |  
-- | -- | -- | --
host.krobis-iotvm | 2021-04-06 15:07:32.387 | info | Updating repository "beta" under "http://download.iobroker.net/sources-dist-latest.json"
mielecloudservice.0 | 2021-04-06 15:07:06.690 | error | at async main (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:647:13)
mielecloudservice.0 | 2021-04-06 15:07:06.690 | error | at async splitMieleDevices (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:273:9)
mielecloudservice.0 | 2021-04-06 15:07:06.690 | error | at async parseMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:295:5)
mielecloudservice.0 | 2021-04-06 15:07:06.690 | error | at async addMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:335:17)
mielecloudservice.0 | 2021-04-06 15:07:06.690 | error | at processTicksAndRejections (internal/process/task_queues.js:93:5)
mielecloudservice.0 | 2021-04-06 15:07:06.690 | error | at addMieleDeviceState (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:370:70)
mielecloudservice.0 | 2021-04-06 15:07:06.690 | error | (11172) [main] :actions is not defined, Stacktrace:ReferenceError: actions is not defined
mielecloudservice.0 | 2021-04-06 15:07:05.872 | info | (11172) Setting up devices ...

**Comment by jhartlep** [comment]
Bei mir der gleiche Fehler mit der Version 4.0.1
Mit der Version 3 lief alles
