### ISSUE TITLE
Warnings after update to JS-Controller 3.3.2

### ISSUE THREAD

**Issue by frankbullitt** [Grizzelbee/ioBroker.mielecloudservice#141]
mielecloudservice.0 | 2021-05-01 00:41:08.440 | warn | (2260) State value to set for  "mielecloudservice.0.Washing_machines.000147495762.ACTIONS.Light" has  wrong type "number" but has to be "string"
-- | -- | -- | --
mielecloudservice.0 | 2021-05-01 00:41:08.351 | warn | (2260) State value to set for  "mielecloudservice.0.Washing_machines.000147495762.Schleuderdrehzahl"  has wrong type "string" but has to be "number"
mielecloudservice.0 | 2021-05-01 00:41:08.276 | warn | (2260) State value to set for  "mielecloudservice.0.Dishwashers.000103439096.ACTIONS.Light" has wrong  type "number" but has to be "string"
mielecloudservice.0 | 2021-05-01 00:41:08.209 | warn | (2260) State value to set for  "mielecloudservice.0.Tumble_dryers.000139604311.ACTIONS.Light" has wrong  type "number" but has to be "string"
mielecloudservice.0 | 2021-05-01 00:38:07.761 | warn | (2260) State value to set for  "mielecloudservice.0.Washing_machines.000147495762.ACTIONS.Light" has  wrong type "number" but has to be "string"
mielecloudservice.0 | 2021-05-01 00:38:07.667 | warn | (2260) State value to set for  "mielecloudservice.0.Dishwashers.000103439096.ACTIONS.Light" has wrong  type "number" but has to be "string"
mielecloudservice.0 | 2021-05-01 00:38:07.663 | warn | (2260) State value to set for  "mielecloudservice.0.Washing_machines.000147495762.Schleuderdrehzahl"  has wrong type "string" but has to be "number"
mielecloudservice.0 | 2021-05-01 00:38:07.512 | warn | (2260) State value to set for  "mielecloudservice.0.Tumble_dryers.000139604311.ACTIONS.Light" has wrong  type "number" but has to be "string"

js-controller: 3.3.2
Node.js: 12.22.1
NPM: 6.14.12
Miele-Cloudservice: 4.0.19

**Comment by Grizzelbee** [comment]
Already fixed in development branch.
See #138 and #139.
