### ISSUE TITLE
State "TargetTemperature" of Washing_Machines in Version 4.0.17 is missing

### ISSUE THREAD

**Issue by jupzup** [Grizzelbee/ioBroker.mielecloudservice#142]
No State "TargetTemperature" of Washing_Machines are in Version 4.0.17 available.

**Comment by Grizzelbee** [comment]
This state has been removed in V4.x since it's not supportted by washing maching according to Miele documentation:
![grafik](https://user-images.githubusercontent.com/5459426/116776430-ae265300-aa68-11eb-96c9-bb17e8eb416a.png)

Di you had any benefit of this state priior to V4.x?

**Comment by benjholl** [comment]
Same problem here. 

Prior to 4.x “mielecloudservice.x.Washing machines.xxxxxxx.targetTemperature_0” was reporting correct values to me.
