### ISSUE TITLE
Event-based status request possible?

### ISSUE THREAD

**Issue by alehofde** [Grizzelbee/ioBroker.mielecloudservice#156]
Hi,
great adapter and good work 😊

One question:
Is there a way to create Event-based status request? That means, my polling interval is configured to 10 minutes. For normal operating this is good.
Now I want to start a request based on an IOBROKER event for a specific attribute (for example Status_raw).
Is this possible? How can I achieve this?

It would be great if you can help me with my special request

Thanks,
Alexander

**Comment by Grizzelbee** [comment]
Thnx! 😊 

Hmmm. If I understood you right you like to update the adapter values from the Miele-API by a trigger inside IOBroker.
Right?  E.g.: Monitor some datapoint in IOBroker and if it's changed - then poll the Miele-API.

Currently this is not possible - and for now I have no plans to implement such a behavior.
But ... I'm working on Event based updates for the adapter. That means: The values in the adapter won't be updated by polling the API in some time interval anymore, but get updated anytime there is a change of any device state. Means: The updates are triggered by Miele-Servers and you can rely on the values at any time without the need to insert an extra poll.

Would that solve your request?

If not - there may be some kind of solution - doing some weird stuff: If the monitored DP changes - you may stop the adapter, start it again and wait approx. 2 seconds. At the start of the adapter all data get updated. This may be your desired extra poll. 😉

**Comment by alehofde** [comment]
Hi Grizzelbee,

yes you understood my requirement correct.
Your idea with the adapter restart in IOBROKER was mine too but the problem what I see, in case the restart will happen at frequent intervals, a authentication will be done on each restart and Miele can lock the account data. Not sure if this will be happened, but it can.

But your new development with event based update, triggered by Miele, sounds interesting. Happy to test it soon...

Thanks for your feedback and good luck with the development :-)


Regards,
Alexander

**Comment by Grizzelbee** [comment]
Please check V4.5.0 on github out, if it fits your needs.
Be aware that this is defenately a BETA version.

**Comment by alehofde** [comment]
Feature no longer needed due to the change to push communication the problem has been resolved.

Thanks,
alehof
