### ISSUE TITLE
improvement request: Add option to push new startTime

### ISSUE THREAD

**Issue by Magnus8513** [Grizzelbee/ioBroker.mielecloudservice#163]
As discussed in the forum I would like to push a new startTime to the machine in order to properly use the Smart Grid/Start functionality of my dishwasher making it run at the time of lowest energy prices. The Miele API documentation says this value can be edited, but changing it in the states today, does not result in a push to Miele, but just gets overwritten at next update with the old value.

see forum discussion here:
[https://forum.iobroker.net/topic/29836/mielecloudservice-adapter/356](url)

**Comment by Grizzelbee** [comment]
Should work with V6.0.0. Please open a new or reopen this issue if not.
