### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by aski71** [Grizzelbee/ioBroker.mielecloudservice#199]
I experience the following issue since tonight. This error message loops and loops:

mielecloudservice.0 | 2022-02-16 10:27:15.664 | error | [addMieleDeviceState]: Cannot read properties of undefined (reading 'targetTemperature'), Stacktrace: TypeError: Cannot read properties of undefined (reading 'targetTemperature') at addMieleDeviceState (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:571:156) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async addMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:330:17) at async parseMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:277:5) at async splitMieleDevices (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:146:9)
-- | -- | -- | --
mielecloudservice.0 | 2022-02-16 10:27:15.660 | info | The API returned http-error 400: GENERIC_BUSINESS_ERROR for device: [007116614756].
mielecloudservice.0 | 2022-02-16 10:27:15.385 | info | Server Sent Events-Connection has been (re)established @Miele-API.
mielecloudservice.0 | 2022-02-16 10:27:15.242 | info | Registering for appliance events at Miele API.
mielecloudservice.0 | 2022-02-16 10:27:15.241 | error | [addMieleDeviceState]: Cannot read properties of undefined (reading 'targetTemperature'), Stacktrace: TypeError: Cannot read properties of undefined (reading 'targetTemperature') at addMieleDeviceState (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:571:156) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async addMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:330:17) at async parseMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:277:5) at async splitMieleDevices (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:146:9) at async main (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:658:13)
mielecloudservice.0 | 2022-02-16 10:27:15.063 | info | The API returned http-error 400: GENERIC_BUSINESS_ERROR for device: [007116614756].
mielecloudservice.0 | 2022-02-16 10:27:14.611 | info | Setting up devices ...
mielecloudservice.0 | 2022-02-16 10:27:14.608 | info | Access-Token expires at: [Fri Mar 18 2022 10:27:14 GMT+0100 (Mitteleuropäische Normalzeit)]
mielecloudservice.0 | 2022-02-16 10:27:14.182 | info | Login attempt #1 @Miele-API
mielecloudservice.0 | 2022-02-16 10:27:14.095 | info | starting. Version 5.0.4 in /opt/iobroker/node_modules/iobroker.mielecloudservice, node: v16.14.0, js-controller: 4.0.10

**Comment by Grizzelbee** [comment]
Hi @aski71 

sorry - I have overseen this issue.
Hmm. I am seeing similar issues from time to time at sentry and I'm not sure what happens there in detail. Looks like the API is sending no data. I think it's time to make the code and error handling more bullet proof. But this will take some time.

is the adapter working for you again or is it still failing?

**Comment by Grizzelbee** [comment]
Intermediate Info: I'm currently working on a new version that will hopefully fix this and other issues. Please be patient since the release will not happen too soon, since it's an almost complete rewrite of the adapter.

**Comment by Grizzelbee** [comment]
should be fixed in upcommingv6.0.0. Please reopen if not.
