### ISSUE TITLE
cm6160 - startet immer beim adapter start

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.mielecloudservice#207]
serwus

seit dem update auf js-controller 4 startet meine Kaffeemaschine immer wenn der adapter startet.

js-controller 4.0.19 (auch schon in den beta Versionen)

**Comment by Grizzelbee** [comment]
Hmm. Habe ich gerade selbst ausprobiert und kann das bestätigen. Muss ich mal ins Log schauen ob bzw. was ich da finde. Schon ulkig das der controller da etwas auslöst.

**Comment by kopierschnitte** [comment]
Ich kann das bestätigen für eine CVA7845.
Adapter 5.0.4

**Comment by Grizzelbee** [comment]
Zwischeninfo: Ich arbeite gerade an einer neuen Version, die dieses und weitere Probleme addressiert. dauert aber noch ein bisschen, weil ich den Adapter dafür quasi komplett neu schreibe.
