### ISSUE TITLE
Delay zwischen Anmeldeversuchen wird nicht beachtet

### ISSUE THREAD

**Issue by rassel2000** [Grizzelbee/ioBroker.mielecloudservice#213]
Hi,
der Adapter beachtet bei mir die 60 Sekunden Verzögerung zwischen den Loginversuchen nicht, sondern "müllt" den Log sekündlich mit Fehlermeldungen zu, falls er keine Verbindung zur Miele API aufbauen kann.
Ich hatte heute für mehrere Stunden einen Internetausfall und war leider nicht Zuhause. Mein Log war nach knapp 4 Stunden 15GB (!) groß und der RasPi einmal abgestürzt aufgrund der Masse an Fehlermeldungen.
Den Log hab ich leider nicht mehr, wäre glaube ich aber auch zu groß gewesen zum Hochladen :)

Adapterversion: 5.0.4
JS-Controller: 3.3.22

Könntest du dir das mal angucken?

Danke und Grüße
Philipp

**Comment by Grizzelbee** [comment]
Hallo Philip,

danke für den Hinweis. Tatsächlich ist mir das auch schon aufgefallen und ich habe das in der Version an der ich gerade arbeite auch bereits gefixed. Da es sich dabei aber um einen kompletten rewrite des Adapters handelt und diese Code-Teile nicht zueinander kompatibel sind, kann ich die aktuelle Verison nicht mal eben so patchen.
Wird aber mit der nächsten Version behoben - versprochen. Die wird insgesamt deutlich robuster werden, als die aktuelle.
