### ISSUE TITLE
mielecloudservice crashes after update to 6.0.0

### ISSUE THREAD

**Issue by aski71** [Grizzelbee/ioBroker.mielecloudservice#225]
`
host.homie | 2022-04-26 20:09:33.784 | info | Do not restart adapter system.adapter.mielecloudservice.0 because disabled or deleted
-- | -- | -- | --
host.homie | 2022-04-26 20:09:33.783 | error | instance system.adapter.mielecloudservice.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
mielecloudservice.0 | 2022-04-26 20:09:33.239 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
mielecloudservice.0 | 2022-04-26 20:09:33.233 | error | adapter disabled
mielecloudservice.0 | 2022-04-26 20:09:33.209 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
host.homie | 2022-04-26 20:09:15.951 | info | "system.adapter.mielecloudservice.0" disabled
host.homie | 2022-04-26 20:09:02.319 | info | Restart adapter system.adapter.mielecloudservice.0 because enabled
host.homie | 2022-04-26 20:09:02.318 | error | instance system.adapter.mielecloudservice.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
mielecloudservice.0 | 2022-04-26 20:09:01.773 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
mielecloudservice.0 | 2022-04-26 20:09:01.772 | info | terminating
mielecloudservice.0 | 2022-04-26 20:09:01.762 | error | Cannot read properties of undefined (reading 'unit')
mielecloudservice.0 | 2022-04-26 20:09:01.762 | error | TypeError: Cannot read properties of undefined (reading 'unit') at Object.module.exports.splitMieleDevices (/opt/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:420:212) at EventSource.<anonymous> (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:102:32) at EventSource.emit (node:events:526:28) at _emit (/opt/iobroker/node_modules/eventsource/lib/eventsource.js:277:17) at parseEventStreamLine (/opt/iobroker/node_modules/eventsource/lib/eventsource.js:292:9) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/eventsource/lib/eventsource.js:249:11) at IncomingMessage.emit (node:events:526:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
mielecloudservice.0 | 2022-04-26 20:09:01.761 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'unit')
mielecloudservice.0 | 2022-04-26 20:09:01.760 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mielecloudservice.0 | 2022-04-26 20:09:01.739 | info | Server Sent Events-Connection has been (re)established @Miele-API.
mielecloudservice.0 | 2022-04-26 20:09:01.636 | info | Registering for all appliance events at Miele API.
mielecloudservice.0 | 2022-04-26 20:09:01.247 | info | Login attempt #1 @Miele-API
mielecloudservice.0 | 2022-04-26 20:09:01.220 | info | starting. Version 6.0.0 in /opt/iobroker/node_modules/iobroker.mielecloudservice, node: v16.14.2, js-controller: 4.0.23
mielecloudservice.0 | 2022-04-26 20:09:01.141 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
host.homie | 2022-04-26 20:09:00.236 | info | instance system.adapter.mielecloudservice.0 started with pid 12884
host.homie | 2022-04-26 20:08:30.190 | info | Restart adapter system.adapter.mielecloudservice.0 because enabled
`

`Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
1996 MHz
Modell
Intel Core i7 9xx (Nehalem Class Core i7)
RAM
7.79 GB
System-Betriebszeit
1 T. 04:46:48
Node.js
v16.14.2 (Empfohlene Version v14.19.1)
time
1650996731724
timeOffset
-120
Anzahl der Adapter
490
NPM
8.5.0
Datenträgergröße
502.35 GB
freier Festplattenspeicher
484.07 GB
Betriebszeit
1 T. 04:46:32
Aktive Instanzen
21
Weg
/opt/iobroker/
Hostname
homie`

**Comment by Grizzelbee** [comment]
Okay. There seems to be something bad inside your devices message, which was covered by the code before and got lost during rewrite. Please do a debug log run and provide the log here. I need to take a deeper look.

**Comment by Grizzelbee** [comment]
@aski71 
After doing some research I'm pretty sure that V6.1.0 will fix your issue.
I removed some useless code for freezers which may have caused the exception. Please give it a try and report the result here. 
But I'm anyways intrested in your debug log - since the device-state and the device-actions messages are logged there. I'd like to collect them to get a kind of device library for adapter testing and debugging purposes.
