### ISSUE TITLE
CVA7845: cannot switch light / light state reversed

### ISSUE THREAD

**Issue by kopierschnitte** [Grizzelbee/ioBroker.mielecloudservice#228]
**Describe the bug**  
When setting ACTIONS.Light to true or false while my CVA7845 coffee machine is powered on, the requested action is not taken and the LastActionResult is
`Light command 'ENABLED (1)' is not available for device with mieleDeviceId 000703374467 and state 2 at this moment. Available light commands: List(DISABLED (2))`

If the machine is powered off, the light switch action seems to be reversed: Setting ACTIONS.Light to false turns light on and setting it to true turns it off.

**Expected behavior**  
The light should be set as requested.

**Versions:**  
 - Adapter version: 6.1.0
 - JS-Controller version: 4.0.23
 - Node version: 14.19.1
 - Operating system: Ubuntu

**Comment by Grizzelbee** [comment]
Tested and confirmed. It's a bug. Fixing it is easy.
