### ISSUE TITLE
Warnings seit Update auf js Version 3.0.14

### ISSUE THREAD

**Issue by Nunmalfix** [Grizzelbee/ioBroker.mielecloudservice#23]
Hallo,
seit dem Update auf JS-Verson 3.0.14 stehen massenweise Einträge in der Art im log: 
mielecloudservice.0 (19977) Object Washing machines.000149130249.ACTIONS.Power On is invalid: obj.common.read has an invalid type! Expected "boolean", received  "string"

oder auch:
 mielecloudservice.0 (19977) Object Washing machines.000149130249.ACTIONS.Nickname is invalid: obj.common.type has an invalid value (String) but has to be one of number, string, boolean, array, object, mixed, file, json

Alle versehen mit dem Hinweis:
 mielecloudservice.0 (19977) This object will not be created in future versions. Please report this to the developer.

Daher der issue ;-)

**Comment by mk176** [comment]
I've got the same warnings since i've updated to js-controller 3

**Comment by forelleblau** [comment]
Bei mir ebenso, der langen Liste nach zu urteilen, sind es wahrscheinlich fast alle Objekt, die aufgeführt sein.

**Comment by Grizzelbee** [comment]
Okay. Danke für die Info. Gucke ich mir an.

**Comment by Grizzelbee** [comment]
Fixed in V1.2.1
