### ISSUE TITLE
6.1.3 targetTemperatur setzen: Unable to process JSON

### ISSUE THREAD

**Issue by pacco81** [Grizzelbee/ioBroker.mielecloudservice#233]
Hi !
Mit 6.1.3 startet der Adapter jetzt wieder sauber durch und liest alle Daten die ich von den Vorversionen kenne.

Beim Schreiben von targettemp für den Gefrierschrank kommt jedoch  "Unable to process JSON". Mit den Vorversionen lief das Setzen der Zieltemperatur nach viel Arbeit von dir zuletzt gut.

Besten Gruß,
Sebastian
[iobroker.2022-05-02.log](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/8604830/iobroker.2022-05-02.log)

**Comment by Grizzelbee** [comment]
>Beim Schreiben von targettemp für den Gefrierschrank kommt jedoch "Unable to process JSON". Mit den Vorversionen lief das Setzen der Zieltemperatur nach viel Arbeit von dir zuletzt gut.

Jaaaa - ich erinnere mich. ;o)
Die TargetTemp ist irgendwie immer etwas kniffelig.

Diesmal ist der Fix aber einfach.

**Comment by pacco81** [comment]
Sauber. TargetTemp setzen über Adapter klappt jetzt. Tausend Dank !
