### ISSUE TITLE
Lightswitch for hood not working

### ISSUE THREAD

**Issue by mi1985** [Grizzelbee/ioBroker.mielecloudservice#250]
**Describe the bug**  
The hood is off, but the light is on. Before was it possible to switch off the light via the object "light". 

**To Reproduce**  
The fan from the hood is off. 
Press the hood light on button 
Wait until the object "light" change to true
Change the object "light" from true to false
Error Message in the Iobroker log "States user redis pmessage io.mielecloudservice.0.000152745591.ACTIONS.*/io.mielecloudservice.0.000152745591.ACTIONS.LastActionResult:{"val":"Light command 'ENABLED (1)' is not available for device with mieleDeviceId 000152745591 and state 5 at this moment. Available light commands: List(DISABLED (2))","ack":true,"ts":1653073158172,"q":0,"from":"system.adapter.mielecloudservice.0","user":"system.user.admin","lc":1653073158172}
"
Error Message from the object LastActionResult: Light command 'ENABLED (1)' is not available for device with mieleDeviceId 000152745591 and state 5 at this moment. Available light commands: List(DISABLED (2))

**Expected behavior**  
Turn off and on the light from the hood via Object "light" (was possible - I guess version 5 of the adapter)

**Versions:**  
 - Adapter version: v.6.2.2
 - JS-Controller version: 4.0.23
 - Node version: v14.19.1
 - Operating system: Ubuntu 18.04.6 LTS

**Comment by Grizzelbee** [comment]
@mi1985 

> Light command 'ENABLED (1)' is not available for device with mieleDeviceId 000152745591 and state 5 at this moment. Available light commands: List(DISABLED (2))

This message is the answer from the API directly. So it says that the prerequsites to switch the light are not met.
Please double check it and provide a debug-log showing the start of the adapter, cheching the switch and shutting the adapter down. Since I don't own a hood I can't reproduce it on my own.
But ... with my coffee machine the light switch works - but not when it's powered off.
When I try to switch the light with the appliance powered off I get:
> Light command 'DISABLED (2)' is not available for device with mieleDeviceId 000153002737 and state 1 at this moment. Available light commands: List(ENABLED (1))

**Comment by mi1985** [comment]
OK, interesting, has something been changed in the API? Previously, this was possible without any problems. I attached the debug log. 
[Debug_Hood.txt](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/8749227/Debug_Hood.txt)

**Comment by Grizzelbee** [comment]
> OK, interesting, has something been changed in the API? Previously, this was possible without any problems

Not as far as I know. But I don't have more information than you have. I'm just a simple Miele customer like you.

>  I attached the debug log.

I can see the start of the adapter - but no switching events or anything else.
Please log the start, some switching events and the shutdown of the adapter. And ... debug is enough - silly events are only confusing. If you run your broker on linux a `cat iobroker.current.log | grep miele > ioBroker.miele.log` will filter the log for you.

**Comment by mi1985** [comment]
I tried to chatch the log. I did the following: 
Adapter stop
Adapter start
Hood Light on - manually on the device: ok
Wait until the the light object in the iobroker changed from false to true
Hoot light off - via iobroker, change Object mielecloudservice.0.000152745591.ACTIONS.Light from true to false: not possible
Hood power on - manually on the device: ok
Wait until the the power object changed from false to true
Hood light off via iobroker, change Object mielecloudservice.0.000152745591.ACTIONS.Light from true to false: not possible
Hood Power off - manually on the device: ok
Hood Light off - manually on the device: ok

[ioBroker.miele.log](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/8751717/ioBroker.miele.log)

**Comment by Grizzelbee** [comment]
The functionalty of this switch got broken due to the changes in #228. 
Fixed in V6.3.0 - should work fine now (again).
Thanks for finding and reporting this bug.

**Comment by mi1985** [comment]
I updated the adapter right now. I can confirm - it works now (indepentend of the power status of the hood)
Many thanks for the support
