### ISSUE TITLE
V6.3.2 ACTIONS.targetTemperatureZone-1" has value "-28" less than min "-26"

### ISSUE THREAD

**Issue by pacco81** [Grizzelbee/ioBroker.mielecloudservice#257]
Hi !

Bei meinem Gefrierschrank kann ich runter bis  -28 °C am Gerät oder der App einstellen.

Der Adapter erwartet wohl nur bis -26. und wirft bei jedem Poll den Fehler im Log

....ACTIONS.targetTemperatureZone-1" has value "-28" less than min "-26"

Vermutl. müssen die Stammdaten im Adapter angepasst werden ?

Besten Dank und Gruß,
Sebastian

**Comment by Grizzelbee** [comment]
Hmmm. Das ist tatsächlich kein Problem des Adapters. 
Die Min/Max Werte liefert die API selbst und von dort übernehme ich sie:

```
"Gefriergerät": {
      "processAction": [
        4
      ],
      "light": [],
      "ambientLight": [],
      "startTime": [],
      "ventilationStep": [],
      "programId": [],
      "targetTemperature": [
        {
          "zone": 1,
          "min": -26,
          "max": -16
        }
      ],
      "deviceName": true,
      "powerOn": false,
      "powerOff": true,
      "colors": [],
      "modes": [
        1
      ]
    },
``` 

Das kannst Du checken, wenn Du den Adapter mal kurz im Debug-Modus startest. Dort findest Du dann ACTIONS nachrichten. Da steht das dann wie gezeigt drin.
Wenn Du willst kannst Du mir gerne die kompletten Gerätedaten schicken; dann kann ich das als Bug an Miele melden.

**Comment by Grizzelbee** [comment]
Wenn Du das Objekt direkt bearbeitest und nur den Max-Wert anpasst müsste das eigentlich klappen. Ich bin mir aber nicht hunterprozentig sicher. Probier es einfach aus. Zur Not müsstest du halt für die Zeit auf -26° hoch gehen - das sollte aber eigentlich kein ensteres Problem für den Inhalt des Schrankes darstellen ;o).

**Comment by Grizzelbee** [comment]
Hat sich hier seitens Miele eigentlich irgendetwas ergeben/getan?
