### ISSUE TITLE
Check en-/decryption of passwords

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.mielecloudservice#271]
As reported/investigated in #269 something happend to the en-/decryption of passwords.

todo: Investigate deeper what happend and whether passwords are still encrypted correctly.

**Comment by Grizzelbee** [comment]
Hallo @krobipd 

soweit ich das gelesen habe ist das ein Bug in Admin 6.2.x und nicht im Miele Adapter. Deshalb habe ich die Verschlüsselung der V6.3.2 wieder hergestellt - schließlich funktioniert die seit einiger Zeit und bei vielen Usern. Probiere bitte mal ob es mit einer Admin v6.1.x oder v6.0.x funktioniert. Oder gar einer V5.x.x. Dann wissen wir mehr und sehen weiter.

**Comment by GermanBluefox** [comment]
Wenn man `encryptedNative` in io-package.json definiert, dann muss man nicht die Werte noch mal decoden.
Die Werte sind schon im onReady decoded:
![image](https://user-images.githubusercontent.com/4582016/180068488-c365a7cd-63eb-4081-9d31-1d76df5af165.png)

**Comment by Grizzelbee** [comment]
@GermanBluefox 

encryptedNative habe ich drin, seit es angeboten wird. Das habe ich damals unter Anleitung und Review durch @Apollon77 eingebaut. Das hat aber nicht komplett funktioniert - sprich: die verschlüssleten Felder wurden nicht entschlüsselt. Deshalb das (zusätzliche) decrypten.

Davon abgesehen funktioniert das (wie mir gesagt wurde) bei value2Table und table2Value eh nicht. Und da habe ich gerade im Wireguard Adapter im Grunde das selbe Problem: https://github.com/Grizzelbee/ioBroker.wireguard/issues/36 
Da bekomme ich nur noch ein Promise-Objekt statt, wie bisher, die Daten. Das Prblem mag also auch an meinen Adaptern liegen - aber nicht alleine. Irgendetwas Grundlegendes hat sich in dem Zusammenhang im Admin 6 geändert. 

![grafik](https://user-images.githubusercontent.com/5459426/180145112-f7a801ef-63c1-4a01-8c93-97b4f41ea5af.png)

**Comment by Apollon77** [comment]
The issue is that you added encryptedNatove but you did NOT removed the encrypt/decrypt in your index_m ...https://github.com/Grizzelbee/ioBroker.mielecloudservice/blob/master/admin/index_m.html#L79

Thats why the values get now encrypted twice ... and thats why also nees to be decrypted twice.

So in fact only solvable nby a release which fixes this and requtred user to reenter password

**Comment by Apollon77** [comment]
Ok, to continue structured:
* when you set a password value in admin and save the config ... please checkhow the system.admin.X.Y object is looking ... for the password fields
* and after saving that and restarting adater the adapter only gets that promise output? Please log it with JSON.stringify to see if it is "the string" or if it is really "the promise object"

**Comment by Apollon77** [comment]
PS: @Grizzelbee And you are sure that index_m was uploaded after changing and such? ;-)) (just to be sure)

**Comment by Grizzelbee** [comment]
> And you are sure that index_m was uploaded after changing and such? ;-)) (just to be sure)

Yes I am. I have my routines when coding and more than double checked it.

What I found so far:

* when I enter something to an encrypted field NEWLY - it gets properly decrypted automatically in the backend
* when I open the config dialog again the encrypted fields aren't restored in clear text but show the string "[object promise]". When I change any field but an encrypted and save the config - the original content of the encrypted fields gets lost and the string "[object promise]" will be encrypted and decrypted in the backend.

These Load / save functions I used in the config dialog (old style with removed de-/encryption)

Load:
```
        // This will be called by the admin adapter when the settings page loads
        function load(settings, onChange) {
            // example: select elements with id=key and class=value and insert value
            if (!settings) return;

            $('.value').each(function () {
                var $key = $(this);
                var id = $key.attr('id');

                if ($key.attr('type') === 'checkbox') {
                    // do not call onChange direct, because onChange could expect some arguments
                    $key.prop('checked', settings[id])
                        .on('change', () => onChange());
                } else {
                    // do not call onChange direct, because onChange could expect some arguments
                    console.log('ID='+id+', settings[id](stringified)='+JSON.stringify(settings[id]));
                    $key.val(settings[id])
                        .on('change', () => onChange())
                        .on('keyup', () => onChange());
                }
            });
            onChange(false);
            // reinitialize all the Materialize labels on the page if you are dynamically adding inputs:
            if (M) M.updateTextFields();
        }
```

save function:
```        // This will be called by the admin adapter when the user presses the save button
        function save(callback) {
            // example: select elements with class=value and build settings object
            var obj = {};
            $('.value').each(function () {
                var $this = $(this);
                var id = $this.attr('id');

                if ($this.attr('type') === 'checkbox') {
                    obj[id] = $this.prop('checked');
                } else if ($this.attr('type') === 'number') {
                    obj[id] = parseFloat($this.val());
                } else {
                    obj[id] = $this.val();
                }
            });
            callback(obj);
        }
```

when stringifying the fields I receive:
```
ID=Miele_account, settings[id](stringified)="h[...]@[...]n.de"
ID=Client_ID, settings[id](stringified)="4968e4b7-[...]4bea759"
ID=Miele_pwd, settings[id](stringified)="$/aes-192-cbc:5b3ffebe313419b618c1a14170556842:914f632d8b944feba057ef3566ba1ca91f803c9492d8078542b08be7c0b99f34" 
ID=Client_secret, settings[id](stringified)="$/aes-192-cbc:4f243263d55e6c2f766ef808704d4b10:d011b7f49a52611ade00c380de869fa3"
ID=messageDelay, settings[id](stringified)=2000
ID=oauth2_vg, settings[id](stringified)="de-DE"
```

**Comment by Apollon77** [comment]
Ahh ok, now we have a point maybe .. please craete an admin issue ... it seems that the decryption in Admin is the issue

**Comment by rabbit6984** [comment]
Schliesse mich an
Admin 6.2.4
Miele 6.3.3
alles funktioniert
Miele 6.3.4 Kein Connect Adapter geht auf Rot und ich solle wieder die Credentials checken.

Somit wieder Downgrade auf 6.3.3 und funktioniert direkt wieder!

**Comment by krobipd** [comment]
fixed with admin 6.2.6
https://github.com/ioBroker/ioBroker.admin/releases/tag/v6.2.6

**Comment by rabbit6984** [comment]
Hi,

update:

Admin v6.2.13
Miele 6.3.3
works fine
Miele 6.3.4 
same Problem not working

**Comment by Grizzelbee** [comment]
@rabbit6984 
I have to disagree. 
MieleCloudService V6.3.4 and <= 6.3.2  work properly with (at least) Admin V6.2.14 and are expected to work with admin  >=V6.2.6. Even an update from 5.0.4 to 6.3.4 works without the need to reenter the passwords with admin 6.2.14. Threfore this is the intended and stable combination.

MieleCloudService V6.3.3 should **NOT** be used since the decryption of passwords is broken. V6.3.2 and V6.3.4 are mostly identical - esp. regarding de-/encryption of passwords.

**Comment by rabbit6984** [comment]
Hi.
so i updated to Admin 6.2.14 and then to Miele 6.3.4
First try same error in the logs. No Loggin possible.
Then i reenter login credentials in the adapter and save them again.
Now the Problem is solved an i connected to api

thanks kind regards
