### ISSUE TITLE
 error [refreshMieledata] {}

### ISSUE THREAD

**Issue by 7oku** [Grizzelbee/ioBroker.mielecloudservice#28]
Installed that adapter for the first time. A washing machine is visible in the Miele@Mobile app already, configured credentials, adapter goes green, but does not show any new objects. iobroker log just shows that output:

```
mielecloudservice.0 | 2020-08-12 15:51:50.977 | error | (31643) [refreshMieledata] {}
mielecloudservice.0 | 2020-08-12 15:51:50.773 | info | (31643) Starting Polltimer with a 3 Minutes interval.
mielecloudservice.0 | 2020-08-12 15:51:50.772 | info | (31643) Access-Token expires at: [Fri Sep 11 2020 15:51:00 GMT+0200 (GMT+02:00)]
mielecloudservice.0 | 2020-08-12 15:51:50.467 | info | (31643) starting. Version 1.2.4 in /opt/iobroker/node_modules/iobroker.mielecloudservice, node: v12.18.1, js-controller: 3.1.6

```

Am I missing something?

**Comment by Grizzelbee** [comment]
Hmm.
Okay there is an error occuring in the function refreshMieledata.

Please activate the debug-logging in the instance-view in ioBroker for this adapter and show the relevant part with the error.

regards
grizzelbee

**Comment by 7oku** [comment]
Unfortunately i got informed very late about your reply and have not saved any forensics. Version 2.0.0 however works fine, so consider this as fixed.
