### ISSUE TITLE
Ressource Data

### ISSUE THREAD

**Issue by rc-itcon** [Grizzelbee/ioBroker.mielecloudservice#29]
Hello,

is it somehow possible to get the ressource data like used water oder energy as a datapoint?

thanks
Christian

**Comment by Grizzelbee** [comment]
Hi Christian,
I would love to get these information and provide it to the adapter too.
But unfortunately these data are not reported by the Miele API.
Actually I provide **all the data** given by the API. 

As long as Miele does not change anything. It's impossible.
Sorry for that.

regards
grizzelbee

**Comment by Grizzelbee** [comment]
Duplicate to: https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/70
