### ISSUE TITLE
Target Temperatures contain "NULL" for washing machine

### ISSUE THREAD

**Issue by guggu1** [Grizzelbee/ioBroker.mielecloudservice#293]
The target temperature(s) for my washing machine do not seem to be retrieved by the interface. The values are always NULL. See attached screenshot.

Christoph S
[Miele Target Temperature NIULL.pdf](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/9496842/Miele.Target.Temperature.NIULL.pdf)

**Comment by Grizzelbee** [comment]
Hi Christoph,

I'm sorry, but with this few information I'm not able to help you at all.
Please provide more information. At least:
* js-controller version:
* Admin version:
* MieleCloudService version:
* Model / type of your washing machine:

Two things that I have in mind immediately:
* As fas as I know not all washing machines provide the targetTemp field.
* It looks like you are using a rather old version of the adapter.

**Comment by guggu1** [comment]
Hello,

Thanks for responding so quickly.

Here is the requested information:
js-controller version: v6.0.0
admin version: v6.2.20
mielecloudservice version: v6.3.2
washing machine model: W 400-75 CH; see also screenshot with adapter object containing further information.

**In earlier adapter versions the target temperature was correctly indicated**. Unfortunately i don't remember to version after which that no longer worked. Also, in the Miele iOS app the temperature is correctly displayed.

[miele adaptor information.pdf](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/9497012/miele.adaptor.information.pdf)

Christoph S

**Comment by Grizzelbee** [comment]
Please:
* stop the dapter
*  delete the entire object tree of the adapter (from instance level down)
* start the adapter

After that your tree should look similar to the screenshot and you'll find the targetTemp below ACTIONS.

![grafik](https://user-images.githubusercontent.com/5459426/188643989-fd94c246-2f78-430d-9314-27e65d0b691a.png)
