### ISSUE TITLE
Restore mielecloudservice.png -ioBroker Repo BROKEN!

### ISSUE THREAD

**Issue by Apollon77** [Grizzelbee/ioBroker.mielecloudservice#32]
The PNG is still used by the repository, Plese restore the file on GitHub!

https://travis-ci.org/github/ioBroker/ioBroker.repositories/jobs/722150641#L816

**Comment by Grizzelbee** [comment]
Fixed by restoring the file.

**Comment by Apollon77** [comment]
thank you!
