### ISSUE TITLE
Invalid Node version

### ISSUE THREAD

**Issue by looxer01** [Grizzelbee/ioBroker.mielecloudservice#321]
**Describe the bug**  
When I try to add an instance to the miele cloud adapter I am getting an error
(see also attachment) that the adapter requires Node 14.9.0 but my version is 16.18...)

![miele](https://user-images.githubusercontent.com/11609655/201472090-e07c619f-fd54-4347-94e7-a82aba96396d.JPG)

and thats the install log when I try install through github

$ iobroker url Grizzelbee/ioBroker.mielecloudservice --host RR-DEB-iOB --debug
install Grizzelbee/ioBroker.mielecloudservice
NPM version: 8.19.2
Installing Grizzelbee/ioBroker.mielecloudservice... (System call)
npm ERR! code EBADENGINE
host.RR-DEB-iOB Cannot install Grizzelbee/ioBroker.mielecloudservice: 1
ERROR: Process exited with code 25

**Comment by Grizzelbee** [comment]
It's true that the adapter wants to ask for a minimum node version >= 14.0.0 - but in fact it asks for a version compative with 14.0.0.

I'll fix this bug in a future version (and I hope pretty soon).

**Comment by looxer01** [comment]
Thank you. and just a note:  The issue only occurs in the BETA repository. Install in stable works.

**Comment by Grizzelbee** [comment]
Habe gerade die beta-1 der versioin 6.5.0 auf github hochgeladen. Bitte testet mal, ob es jetzt sauber funktioniert.
