### ISSUE TITLE
no update from 4.2 to 6.4.0

### ISSUE THREAD

**Issue by bmause** [Grizzelbee/ioBroker.mielecloudservice#348]
Hallo, 
leider kann ich den Adapter nicht updaten.
<img width="512" alt="Bildschirm­foto 2023-03-14 um 14 22 58" src="https://user-images.githubusercontent.com/105861086/225015368-c9465a47-d877-4902-b63f-3736dd6ebc00.png">

**Comment by Grizzelbee** [comment]
Ja, das ist korrekt und der Bug ist bekannt.
Siehe: https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/321

Ich arbeite im Augenblick an einer neuen Version, die das fixen wird.

So aus purer Neugierde: Darf ich fragen warum Du mit dem Update so lange gewartet hast? Nach der 4.2.0 ist ja doch einiges passiert.

**Comment by bmause** [comment]
Hallo, Danke für deine Rückmeldung.Zu deiner Frage, hatte jetzt erst eine Miele Waschmaschine die ich in Iobroker bringen wollte. Hatte es aber nicht hinbekommen den Adapter zu installieren, weil ich immer Beta stand.Konnte es jetzt aber soweit alles installieren und läuft.Gruß Björn Von meinem iPad gesendetAm 16.03.2023 um 16:15 schrieb Grizzelbee ***@***.***>:﻿
Ja, das ist korrekt und der Bug ist bekannt.
Siehe: #321
Ich arbeite im Augenblick an einer neuen Version, die das fixen wird.
So aus purer Neugierde: Darf ich fragen warum Du mit dem Update so lange gewartet hast? Nach der 4.2.0 ist ja doch einiges passiert.

**Comment by Grizzelbee** [comment]
Habe gerade die beta-1 der versioin 6.5.0 auf github hochgeladen. Bitte testet mal, ob es jetzt sauber funktioniert.
