### ISSUE TITLE
PlateStep wird nicht mehr angezeigt!

### ISSUE THREAD

**Issue by UweLoyal** [Grizzelbee/ioBroker.mielecloudservice#356]
mielecloudservice.0.000XXXXXXXXX.PlateStep_0 bis _5 zeigen keine Werte an (Herdplatte an).
mielecloudservice.0.000XXXXXXXXX.PlateStepZone-0 bis -5 zeigen korrekte Werte an.

![image](https://user-images.githubusercontent.com/5464553/229789578-f98fcc73-0f92-402b-9f45-c4a9bae42768.png)

**Comment by Grizzelbee** [comment]
Das ist korrekt so:

### V6.1.0 (2022-04-27) (Black Wings)
* (grizzelbee) Fix: Added some error handling
* (grizzelbee) Chg: Changed PlateStep_x data structure to PlateStepZone-x
* (grizzelbee) Chg: Removed unused ambientLight function
* (grizzelbee) Chg: [225](https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/225) Removed unused freezerZone code for knownDevices

Das hat sich mit Version 6.1.0 geändert.
Bitte die alten Datenpunkte löschen.

Vielleicht einfach den ganzen Baum löschen und neu anlegen lassen.
Es hat in der Vergangenheit immer mal wieder Änderungen an den Datenpunkten gegeben. Da könnten also noch mehr verwaist sein - Kommt auf deine Geräte und den Versionssprung an.

**Comment by UweLoyal** [comment]
Genau hier liegt das Problem, es wird lediglich die zuletzt eingestellte Stufe angezeigt. Auch wenn man manuell auf Stufe 0 stellt wird das nicht im Objekt gesetzt. 
Gibt es hier eine Lösung?
Wie kann ich sehen, was aus der Cloud für Infos kommen?
Im Objekt Baum gibt es da leider kein z.B. Jason um alles zu sehen.

LG
Uwe

**Comment by Grizzelbee** [comment]
> Die Miele App zeigt übrigens das eingeschaltete Herdfeld.

Das mag sein - die API und die App sind aber nicht funktionsgleich. Die App bietet regelmäßig mehr Informationen als die API. Ein Umstand, den ich schon mehrfach bei Miele adressiert habe.

> Wie kann ich sehen, was aus der Cloud für Infos kommen?
Im Debug-Modus schreibt der Adapter alle Infos, die er bekommt, ins Log raus.
Die Miele-Dokumentation dazu findest Du
* hier: https://www.miele.com/developer/swagger-ui/swagger.html#/
* hier: https://www.miele.com/developer/capabilities.html
* und hier: https://www.miele.com/developer/assets/API_V1.x.x_capabilities_by_device.pdf

Den aktuellen Status des Gerätes (Ein, Aus, mehr ...) findest Du hier:
![grafik](https://user-images.githubusercontent.com/5459426/230002208-08879d36-3d0b-4e8a-9a49-1883c4657213.png)

Ob Du mit Hilfe von Status UND PlateStep herausfinden kannst welche Platte gerade an ist, weiß ich allerdings nicht. Ich selbst besitze kein Kochfeld.

**Comment by UweLoyal** [comment]
Erste Analyse:

**Plattenaufbau KM7575 (6 Zonen Herd)**

1  |  5  |  2
--+---+---
0  |  4  |  3

**Zone 0 auf Stufe**

      "plateStep": [
        {
          "value_raw": 5,
          "value_localized": "3",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        }

**Zone 1 auf Stufe**

      "plateStep": [
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 5,
          "value_localized": "3",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Leistungsstufe"
        }
      ],

**ioBroker Object**

![image](https://user-images.githubusercontent.com/5464553/230032804-b4f503f6-3a75-461c-8e39-6a2e16983fae.png)

Die Werte werden nicht auf 0 gesetzt, wenn die Zone abgeschaltet (inaktiv) ist!

LG
Uwe Loyal

**Comment by Grizzelbee** [comment]
Ich habe tatsächlich einen Fehler gefunden und in der V6.5.0-beta2 gefixed.
Bite installiere die einmal und teste ob sich das Problem damit erledigt hat.

**Comment by UweLoyal** [comment]
Ich habe heute nochmal raumgetestet, ich glaube auch value_raw spielt eine Rolle, man muss ja feststellen können, ob Platten einzeln oder in Gruppe geschaltet wurden.
0+1, 4+5 oder 3+2
Hier muß ich mir aber noch Zeit nehmen und ein bisschen testen.

Zeit, für IT'ler Mangelware  ;-)

LG
Uwe

**Comment by Grizzelbee** [comment]
> Ich habe heute nochmal raumgetestet, ich glaube auch value_raw spielt eine Rolle, man muss ja feststellen können, ob Platten einzeln oder in Gruppe geschaltet wurden. 0+1, 4+5 oder 3+2 Hier muß ich mir aber noch Zeit nehmen und ein bisschen testen. 

Sollte eigentlich keine Rolle spielen. Value_raw und Value_localized sind (zumindest bei anderen Werten) das Selbe - nur in unterschiedlichen (lokalisierten) Interpretationen. Z.B. °F und °C. Warum das bei Kochfeldern abweicht - keine Idee.
Wenn in Gruppen geschaltet wird, würde ich erwarten, das beide Platten der Gruppe jeweils die gleichen Werte haben.

>Gibt es eigentlich Feldbeschreibungen von Miele?

Ja. Wärest  Du den Links gefolgt, die ich heute morgen hier gepostet habe, würdest Du die Frage nicht stellen. Die Beschreibung von Miele habe ich aber jeweils im Feld "Name" hinterlegt.

**Comment by UweLoyal** [comment]
Meine Tests heute haben ergeben, dass nur über das Feld value_localized (PlateStepZone) nicht festzustellen ist, ob die Felder zusammengeschaltet wurden. Ich vermute aber, dass dies zusammen mit dem Feld value_raw möglich ist. Natürlich habe ich die Links mir angeschaut, denn sonst hättest Du heute nicht die obigen Infos erhalten (Miele API Tool). Ich konnte leider noch nicht alles gründlich Durchforsten, so habe ich die Info zu value_raw noch nicht gefunden, deshalb auch meine Frage.
Wir werden das schon zusammen hinbekommen, ich habe ja einen Herd zum Testen    ;-)

Ich werde Deine neue Version versuchen so schnell wie möglich einzuspielen um Dir Rückmeldung zu geben.

LG
Uwe

**Comment by Grizzelbee** [comment]
Das sollte normalerweise klappen - ja.
Ich habe da aber auch schon Murks erlebt.

Im Zweifel alternativ so:'
![grafik](https://user-images.githubusercontent.com/5459426/230166727-8ddb9754-eb13-438b-ba89-98fa13ed5925.png)

**Comment by UweLoyal** [comment]
Schlechte Nachricht, Adapter ließ sich nicht starten!
Hat aber 6.5.0-beta2 angezeigt.
Auch kompletter Start von ioBroker hat nichts gebracht.
Mußte alles deinstallieren, damit die 6.4.0 wieder lief.

LG
Uwe

**Comment by Grizzelbee** [comment]
Der oauth is not a function Bug sollte behoben sein und damit der Adapter wieder starten. Bitte noch einmal testen.

**Comment by UweLoyal** [comment]
Ok, hat jetzt geklappt.
Es hat aber auch interessante Ergebnisse gezeigt!

Hier der erste Test:
**ioBroker Objects:**
![image](https://user-images.githubusercontent.com/5464553/230582213-ebc61a32-6a73-4db6-909f-45890b78b39b.png)

**GET /devices/{deviceId}**
    "plateStep": [
      {
        "value_raw": 0,
        "value_localized": "0",
        "key_localized": "Leistungsstufe"
      },
      {
        "value_raw": 0,
        "value_localized": "0",
        "key_localized": "Leistungsstufe"
      },
      {
        "value_raw": 0,
        "value_localized": "0",
        "key_localized": "Leistungsstufe"
      },
      {
        "value_raw": 110,
        "value_localized": "Warmhalten ",
        "key_localized": "Leistungsstufe"
      },
      {
        "value_raw": 13,
        "value_localized": "7",
        "key_localized": "Leistungsstufe"
      },
      {
        "value_raw": 0,
        "value_localized": "0",
        "key_localized": "Leistungsstufe"
      }

Das interessante dort ist "value_localized": "Warmhalten ", was ja bei type numer zu NULL führt!

Mehr Test's in Kürze

LG
Uwe

**Comment by UweLoyal** [comment]
Habe was in Doku entdeckt!

https://www.miele.com/developer/swagger-ui/index.html unter **Schemas**.
Sieht man nicht auf den ersten Blich, da zugeklappt!

![image](https://user-images.githubusercontent.com/5464553/230596419-43cdfed0-3682-499f-9906-f6fd561012f1.png)

Mein Bachgefühl sagt, dass wir alle Werte (value_raw, value_localized und key_localized) brauchen.

LG
Uwe

**Comment by UweLoyal** [comment]
Ich muss mich korrigieren, an value_raw kann man leider nicht erkennen, ob die Platten zusammengeschaltet sind.
value_raw bestimmt nur die eingestellte Stufe, jedoch als Wert.
Ich glaube das Beste ist, Du setzt  value_localized auf string, dann deckt das alles ab, also auch "Boost 1", "Boost 2" und "Warmhalten".
Was sagst Du dazu?

Hier die Testergebnisse:
![image](https://user-images.githubusercontent.com/5464553/230735061-14a6163d-2d01-40be-a057-1e821d81010a.png)

LG
Uwe

**Comment by Grizzelbee** [comment]
> Ich glaube das Beste ist, Du setzt value_localized auf string, dann deckt das alles ab, also auch "Boost 1", "Boost 2" und "Warmhalten".
> Was sagst Du dazu?

Ja - das gehe ich mit. Das ergibt Sinn so.
Das ist auch analog zu anderen ähnlichen Datenpunkten, wie z.B: das Programm bei Wasch- und Spülmaschinen und Wäschetrocknern. Da wird auch der Programmname in value_localized als sprachlich lokalisierter String (Deutsch/Englisch/...) geliefert (Waschen/Wasching/..., Spülen/Rinse/..., Trocknen/Drying/...) und in Value_raw gibt es eine passende Zahl dazu ( siehe auch: https://github.com/Grizzelbee/ioBroker.mielecloudservice/blob/master/machine_states.md )

Aus diesem Grunde habe ich gerade die beta-4 hochgeladen in der PlateStepZone-x ein String ist und - neu - PlateStepZone-x_raw den entsprechenden value_raw enthält. Alle *_raw* Datenpunkte sind im Adapter IMMER die value_raw des sonst gleichnamigen Datenpunktes. In Skripten bevorzuge ich immer die *_raw* Datenpunkte, weil numerische Vergleiche sicherer funktionieren und schneller gehen als text-(string)-Vergleiche.

Ich bin mir nicht ganz sicher ob die Umstellung auf String so ohne weiteres funktinniert. GGf. musst Du die PlateStepZone-x Datenpunkte einmal löschen und neu anlegen lassen.


> Nachtrag:
state-->spinningSpeed-->value_localized ist auch ein String
Deswegen wird hier auch NULL bei mir angezeigt!

Das verstehe ich nicht ganz. Reden wir über die Schleuderdrehzahl bei Waschmaschinen? Das funktioniert bei mir wunderbar.

**Comment by UweLoyal** [comment]
Laut Miele ist spinningSpeed ein String, bei Dir number, deshalb gibt es auch hier ein Problem.

Deshalb auch meine Empfehlung im Nachtrag.

![image](https://user-images.githubusercontent.com/5464553/232403532-17b5f5f2-7cba-41d9-8121-845033408d5b.png)

![image](https://user-images.githubusercontent.com/5464553/232401667-7219feda-9ebc-4567-8cea-6fe7f6e5f1af.png)

![image](https://user-images.githubusercontent.com/5464553/232401927-ccc3324c-2f74-42c0-ad7b-456e8da495a5.png)

![image](https://user-images.githubusercontent.com/5464553/232402486-31ae33a8-d5ae-4723-82b5-9d99446eea8f.png)

![image](https://user-images.githubusercontent.com/5464553/232402758-4c659bb7-ac93-4ffa-8d57-f0968574358c.png)

**LG
Uwe**

**Comment by UweLoyal** [comment]
Zusatzinfo:

![image](https://user-images.githubusercontent.com/5464553/232413032-3ebb9c12-7d79-4f78-9828-4d3fb1c33388.png)

https://www.miele.com/developer/swagger-ui/put_additional_info.html

![image](https://user-images.githubusercontent.com/5464553/232413759-12e5d733-1170-470d-889d-18eb8bb7ce17.png)

**Comment by Grizzelbee** [comment]
> Laut Miele ist spinningSpeed ein String, bei Dir number, deshalb gibt es auch hier ein Problem.

Das ist zwar grundsätzlich korrekt, aber mir fehlt gerade die Idee was außer einer Zahl da vielleicht stehen könnte.
Ich habe das gerade einmal getestet und (null) steht da, wenn die Maschine noch nie gelaufen ist. Sobald die Maschine einmal gelaufen ist, bleibt da eigentlich immer der letzte Wert stehen - und das funktioniert bislang tadellos.
![grafik](https://user-images.githubusercontent.com/5459426/232426980-2fa25b70-583c-4512-8476-aa78e431ed48.png)


Ungeachtet dessen, ist es lt. Miele-Doku korrekt als String - deshalb habe ich mich entschieden auf String umzustellen und einen *_raw* Datenpunkt hinzugefügt - aber auch die werden erst beim ersten Lauf der Maschine mit Daten befüllt. So lange die Maschine aus ist steht da: (null) - möglicherweise auch wieder nach dem Ausschalten; da hängt davon ab, was Miele dann sendet.

> Ach ja, werden die PlateStepZone-* auf 0 gesetzt, wenn der Herd ausgeschaltet ist/wird?
War Vorschlag von mir.

Keine Ahnung. Das hängt davon ab, was Miele als letzten Wert sendet. Da werde ich nicht reingrätschen. Wenn Status=Aus, ist das Kochfeld eben aus - egal was dann in Platestep steht. Das Selbe gilt ja z.B. auch spinningSpeed. 


> ![grafik](https://user-images.githubusercontent.com/5459426/232428875-1c805c0c-ff0a-42f7-8615-fc60169cf32c.png)


Danke für die Info. Habe den broken-Link entfernt.

**Comment by Grizzelbee** [comment]
Aha. Und was bedeutet das jetzt? Funktionieren die Datenpunkte zu SpinningSpeed und PlateStep jetzt, oder nicht?

**Comment by Grizzelbee** [comment]
> SpinningSpeed geht nach Ende des Waschprogrammes immer auf NULL (siehe eine Antwort vorher).
> PlateStep behält den letzten Zustand (eingestellte Stufe) vor Abschaltung, erst beim Einschalten werden alle auf 0 gesetzt.

Okay. Works as designed. Für mich ist das fein.

> Soll ich jetzt die neue Version Testen, oder muss noch was korrigiert werden?
Bitte kurze Rückmeldung an mich.

Das musst Du selbst entscheiden. Für mich sieht das jetzt alles fein aus und ich bin geneigt das so als Release freizugeben.

**Comment by UweLoyal** [comment]
**Erste Rückmeldung (Kochfeld):**
Jetzt wird auch Boost 1, Boost 2 und Warmhalten angezeigt.
Beim Ausschalten behält er die letzten Stufen.
Beim Einschalten wird dann alles auf 0 gesetzt.
Kann natürlich jetzt über einen Trigger alles auf 0 setzen, wenn Herd aus ist.
User ohne ioBroker können das natürlich nicht, ggf. könne diese dann nur über value_template setzten.
Ob Du das jetzt über Dein Modul jetzt macht oder nicht, das überlasse ich Dir.    ;-)

Die Waschmaschine läuft nach, Ergebnis in Kürze!

LG
Uwe

**Comment by UweLoyal** [comment]
Ist eigentlich die 6.5.0 jetzt öffentlich, wird bei mir noch nicht angezeigt?

LG
Uwe
