### ISSUE TITLE
Status "Main state of the Device" keine Aktualisierung/Änderung

### ISSUE THREAD

**Issue by Knallix** [Grizzelbee/ioBroker.mielecloudservice#377]
**Describe the bug**  
Habe folgendes Problem:
Die beiden States 
mielecloudservice.0.000151788982.Status
mielecloudservice.0.000151788982.Status_raw
aktualisieren sich nicht mehr
Der Rest läuft augenscheinlich normal, z.B. Die Zeit wird angezeigt und läuft auch runter wenn die Waschmaschine läuft usw.

**Expected behavior**  
Habe schon alles getestet:
Neustart / Upload Adapter/ Neues Token etc.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 6.5.4
 - JS-Controller version: 4.0.24
 - Node version: 16.19.1
 - Operating system: Debian

![image](https://github.com/Grizzelbee/ioBroker.mielecloudservice/assets/42406048/2ffdd281-9862-423b-8b74-7dd60670c2f9)

**Comment by Jailobeam** [comment]
Glaube das das ist das selbe Problem wie bei mir das die Api Sprache immer englisch ist egal welche sprache man einstellt

**Comment by Grizzelbee** [comment]
Duplikat zu #376 
Bitte den Issue #376  verwenden - denn: Ja - es ist das selbe Problem.
