### ISSUE TITLE
add "signalDoor" to WashingMashine 

### ISSUE THREAD

**Issue by pacco81** [Grizzelbee/ioBroker.mielecloudservice#402]
Hi !

Könntest du für Waschmaschinen (type label 1) die capability "signalDoor" mit abfragen und als Datenpunkt ausgeben ?

Obwohl die API-PDF sagt, dass die Waschmaschinen die Türdaten nicht haben, so scheint es doch zu gehen: Das HA Plugin fragt den Türstatus bei meiner Waschmaschine problemlos ab. Siehe [https://github.com/HomeAssistant-Mods/home-assistant-miele/blob/dc2c21ce1d7782ebdf6913c8f41600fa6d561c5f/custom_components/miele/__init__.py#L87](url) 

Es scheint wohl ein binärSensor zu seinden HA als offen, zu und nicht-verfügbar übersetzt.

Aktuell habe ich nur für die Tür eine HomematicFensterkontakt, den ich mir dann sparen könnte.

Besten Dank und Gruß !
Sebastian

<img width="364" alt="Bildschirmfoto 2024-05-05 um 21 35 33" src="https://github.com/Grizzelbee/ioBroker.mielecloudservice/assets/29131107/6849c750-ac03-415e-bbb2-35ef7207b533">

**Comment by Grizzelbee** [comment]
Hi !

Tatsächlich hatte ich das in alten Versionen des Adapters drin und habe es später (ich glaube mit der 6er Version) ausgebaut, weil es (zumindest bei mit und lt. Doku) nicht funktionierte.
Bitte probiere mal aus, ob es mit einer 5er oder 4er Version funktioniert - dann baue ich das gerne wieder ein.
Allerdings kennt die Miele-API keine binären Switches - das sind boolsche Switches, die true/false als Text schicken. Ist halt JSON, was von der API kommt. 

Du könntest auch ein Debug-Log schreiben und Dir die Nachrichten, die von der API kommen ansehen ob sich signalDoor bei Dir je nach Türstatus ändert.

**Comment by pacco81** [comment]
Hi !
Ja, im iobroker Debug ändert sich der Status beim Öffnen der Tür auf true. Geschlossen ist false.

Mein Gerät ist übrigens WWG760 Firmware: 08.23 Hardware: EK057 

Vielen Dank !

**Comment by Grizzelbee** [comment]
Habe ich in V6.5.6 implementiert.
Sollte ab morgen im latest repo zu finden sein.

**Comment by pacco81** [comment]
Klappt ! Besten Dank für die Weiterentwicklung !
