### ISSUE TITLE
log errors 

### ISSUE THREAD

**Issue by koburg** [Grizzelbee/ioBroker.mielecloudservice#45]
I got these errors in the log anything to do about them ?

`

mielecloudservice.0 | 2020-10-18 12:18:50.612 | error | at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
mielecloudservice.0 | 2020-10-18 12:18:50.612 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:236:41)
mielecloudservice.0 | 2020-10-18 12:18:50.612 | error | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5215:29)
mielecloudservice.0 | 2020-10-18 12:18:50.612 | error | at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8257:29)
mielecloudservice.0 | 2020-10-18 12:18:50.612 | error | at Object.unload (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:54:21)
mielecloudservice.0 | 2020-10-18 12:18:50.612 | error | at APILogOff (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:871:67)
mielecloudservice.0 | 2020-10-18 12:18:50.612 | error | (2971) ReferenceError: err is not defined
mielecloudservice.0 | 2020-10-18 12:18:50.611 | error | (2971) unhandled promise rejection: err is not defined
Unhandled | 2020-10-18 12:18:50.610 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mielecloudservice.0 | 2020-10-18 12:18:50.609 | error | at processImmediate (internal/timers.js:461:21)
mielecloudservice.0 | 2020-10-18 12:18:50.609 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:236:41)
mielecloudservice.0 | 2020-10-18 12:18:50.609 | error | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5215:29)
mielecloudservice.0 | 2020-10-18 12:18:50.609 | error | at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8257:29)
mielecloudservice.0 | 2020-10-18 12:18:50.609 | error | at Object.unload (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:51:21)
mielecloudservice.0 | 2020-10-18 12:18:50.609 | error | at APILogOff (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:871:67)
mielecloudservice.0 | 2020-10-18 12:18:50.609 | error | (2971) ReferenceError: err is not defined
mielecloudservice.0 | 2020-10-18 12:18:50.602 | error | (2971) unhandled promise rejection: err is not defined
Unhandled | 2020-10-18 12:18:50.601 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

`

**Comment by Grizzelbee** [comment]
Thanks for opening this issue. I already noticed this errors in my own log too but haven't any time to investigte on them. Let's take this issue as a reminder. I will take care of it, when I find some time.

**Comment by Grizzelbee** [comment]
duplicate to #58
