### ISSUE TITLE
ecofeedback Object => aka "Implement Miele API 1.0.4"

### ISSUE THREAD

**Issue by artcrime** [Grizzelbee/ioBroker.mielecloudservice#70]
Hi,

would it be possible to add the ecofeedback variables into the iobroker object tree? I contacted Miele a few days ago and they told me that there are new variables about consumption of water and power.

ecoFeedback JSON | ecoFeedback Definition

"ecoFeedback": {    "currentWaterConsumption": {      
"unit": "l",      "value": 0    },    
"currentEnergyConsumption": {      "unit": "kWh",      "value": 0    },    
"waterForecast": 0.2,    "energyForecast": 0.1  },

Regards

**Comment by Grizzelbee** [comment]
Is already on the list - known as "Implement Miele API 1.0.4".
So: Yeah - it up to come! As soon as I find some time for it.

**Comment by artcrime** [comment]
great work! thanks in advance

**Comment by rc-itcon** [comment]
Hi,

installed version 3.0.0 and delete the tree from mielecloud -> create/refresh the tree but still no ecofeedback Datapoints there.

regards
Christian

**Comment by Grizzelbee** [comment]
@rc-itcon Yeah. They currently appear on the first run of the device since that's the first time they deliver data. Actually I'm thinking about changing that and create them with default values on startup.
