### ISSUE TITLE
Leerzeichen im Objektordner Washing Machine

### ISSUE THREAD

**Issue by OriginalGoschi** [Grizzelbee/ioBroker.mielecloudservice#73]
Hallo,

ist es möglich in einem zukünftigen Update das Leerzeichen im Objektordnernamen zu entfernen?
Ich habe keinerlei Möglichkeit unsere Waschmaschine in unsere Visualisierung einzubinden. Oder gibt es da ne möglichkeit?
Liebe Grüße
Goschi

**Comment by Grizzelbee** [comment]
Hmmm. Klar geht das. Ich frage mich nur gerade inwiefern das Probleme in VIS verursachen sollte. 
Für mich funktioniert das aktuell prima und ich habe auch noch keine anderen Klagen gehört.
Kannst Du deine Schwierigkeiten vielleicht etwas genauer beschreiben?

**Comment by OriginalGoschi** [comment]
Danke für die schnelle Antwort. Ich benutze die Jarvis Visualisierung. Wenn ich dort einen neuen Datenpunkt anlegen will erhalte ich folgenden Fehler:
![image](https://user-images.githubusercontent.com/78853632/107510430-38ff5c00-6ba4-11eb-8de9-42b5b26ff37b.png)

**Comment by Grizzelbee** [comment]
Okay. Verstehe.
Das trifft dann alle "Gruppen-Folder" und auch ein paar Aktionen. Power on/off habe ich gerade auf die Schnelle gesehen. Vielleicht ein paar mehr.
Ich nehme das mal mit auf die Liste fürs nächste Release.

**Comment by OriginalGoschi** [comment]
Vielen Dank! ;-)

**Comment by Grizzelbee** [comment]
Was du vielleicht bis dahin als Überbrückung versuchen könntest: Versuch mal ob du den kompletten Datenpunkt von vorne bis hinten in "" packen kannst. Also "mielecloudservicer.0.....RemainingTime". Bei Windows-Pfaden klappt das. ;-)

**Comment by OriginalGoschi** [comment]
Leider nicht, die Jarvis Visualisierung scheint das zu prüfen. Kann man auf Objekte Aliase setzen?

**Comment by Grizzelbee** [comment]
> Kann man auf Objekte Aliase setzen?

Habe ich noch nicht probiert. Keine Ahnung.
