### ISSUE TITLE
Gefrierschrank FN 29474 ws: Target_Temperature ändern ?

### ISSUE THREAD

**Issue by pacco81** [Grizzelbee/ioBroker.mielecloudservice#90]
Hallo zusammen !

Der Adapter v.3.0.1  hat meinen Gefrierschrank FN 29474 ws mit WLAN ModulXKS 3100 W erkannt und alle Daten problemlos ausgelesen. Vielen Dank für die Entwicklung.

Steuern kann ich über Actions jedoch nur Stop und Start_Superfreezing. Ich würde gerne die target_temp. einstellen, so wie es auch über die Miele iOS App geht.

Wird dies über die API nicht unterstützt ? Aus der Doku werde ich bei PUT dazu nicht schlau.
Kann gerne logs, Screenshots usw liefern.

Besten Dank und Gruß,
Sebastian

**Comment by Grizzelbee** [comment]
Hallo Sebastian,

ich würde dich gerne mit der Sache noch einen Augenblick vertrösten und einladen den Adapter mit mir zu testen.
Will sagen: Ich bin kürzlich über ein Miele Dokument gestolpert, das endlich einmal klar sagt, welche Geräte welche States und welche Aktionen unterstützen. 
Ich bin gerade dabei das alles in einer V4.0.0 möglichst sauber umzusetzen. Die States sind auch schon fertig - ich suche nur noch nach einem guten Weg die Actions zu implementieren.

Also kurz: Ja - es kann gut sein, dass die V3.0.1 das noch nicht unterstützt. Die V4.0.0 wird es können - aber da arbeite ich eben gerade erst dran.

**Comment by pacco81** [comment]
Hi Grizzelbee !

Vielen Dank für die Rückmeldung. Das hört sich ja gut an.
Ich kann dann beim Testen gerne helfen, wenn es so weit ist. Beim Programmieren kann ich mangels knowhow leider nicht beitragen.

Besten Dank und Gruß,
Sebastian

**Comment by Grizzelbee** [comment]
Hallo Sebastian,
die Arbeiten schreiben voran und es fehlen nicht mehr viele Sachen ... Deswegen habe ich eine Bitte:
Kannst Du den Adapter bitte einmal in den Debug-Modus bringen und mir das erste große JSON, das nach dem Login kommt auf dem Log hier posten? Du musst das allerdings aus der "Log-Herunterladen" Ansicht holen. In der normalen Log-Ansicht wird das abgeschnitten.

**Comment by pacco81** [comment]
Hi ! 
Hier der Log mit V3.0.2. Die Serial und Matnr. habe ich verfremdet.

**Comment by Grizzelbee** [comment]
Habe gerade mal die V4.0.0 zum testen freigeschaltet. Installation über das git (katzen) icon in der Adapter-Ansicht.

**Comment by pacco81** [comment]
HI !
Habe 4.0.0 installiert und alle Objekte der alten Version gelöscht. Neue Objekte werden angelegt. S.Foto. Log zeigt u.A.Folgendes :

2021-03-18 13:37:21.490  - [34mdebug[39m: mielecloudservice.0 (7913) createArray:  OrgUnit: [Celsius]
2021-03-18 13:37:21.490  - [34mdebug[39m: mielecloudservice.0 (7913) [createNumber]: Path[Freezers.711762131.Temperature_2] Value[null] Unit[Celsius]
2021-03-18 13:37:21.490  - [34mdebug[39m: mielecloudservice.0 (7913) [createNumber]: invalid value detected. Skipping...
2021-03-18 13:37:21.492  - [31merror[39m: mielecloudservice.0 (7913) [addMieleDeviceState]: Cannot read property '1' of undefined, Stacktrace: TypeError: Cannot read property '1' of undefined
    at addMieleDeviceState (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:545:132)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:335:17)
    at async parseMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:295:5)
    at async splitMieleDevices (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:273:9)
    at async Timeout.schedule [as _onTimeout] (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:637:21)

<img width="1107" alt="Bildschirmfoto 2021-03-18 um 13 38 45" src="https://user-images.githubusercontent.com/29131107/111627435-5781f400-87ef-11eb-85ef-fdf887cf577c.png">

**Comment by Grizzelbee** [comment]
Habe das gerade mal versucht zu fixen.
Bitte einmal updaten und erneut versuchen.

**Comment by pacco81** [comment]
Das geht ja sauschnell. Danke !
Die Versionsummer ist nach dem drüberinstallieren bei 4.0.0 geblieben, richtig ?

Super Freezing ist wieder da. Leider kommt  target_temp immer noch nicht.
[log.txt](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/6166848/log.txt)

<img width="1165" alt="Bildschirmfoto 2021-03-18 um 20 39 26" src="https://user-images.githubusercontent.com/29131107/111687843-0db6ff00-882b-11eb-8032-7415030ce22b.png">


Es fällt auf:
[createNumber]: invalid value detected. Skipping...

**Comment by Grizzelbee** [comment]
Hoffe das das jetzt funktioniert. Falls nicht ... bitte weiter bohren. Falls ja: Bitte Issue schließen.

**Comment by pacco81** [comment]
Hi ! Dank fürs weitertüfteln:

Habe nochmal über die Katze neuinstalliert. Es zeigt die V.4.0.1 
Leider kommen wieder Fehler:

<img width="1247" alt="Bildschirmfoto 2021-04-06 um 22 19 23" src="https://user-images.githubusercontent.com/29131107/113773543-760c4880-9726-11eb-8662-ea1fc06ff546.png">
<img width="1166" alt="Bildschirmfoto 2021-04-06 um 22 18 53" src="https://user-images.githubusercontent.com/29131107/113773551-773d7580-9726-11eb-8b3d-612ddbb7ad92.png">

**Comment by Grizzelbee** [comment]
Okay. Ich wechsel mal auf die Politik der kleinen Schritte und ändere nur noch wenig pro Release...
Der Fehler hatte nichts mit der TargetTemp zu tun. Bitte der v4.0.2 eine Chance geben. ;o)

**Comment by Grizzelbee** [comment]
Im Forum erzählt man sich, das die V4.0.3 einen Versuch wert wäre. ;)

**Comment by pacco81** [comment]
Hi ! Danke für die Geduld.

Leider sagt die 4.0.4  das:

07 18:50:04.187  - debug: mielecloudservice.0 (12005) [createNumber]: Path[Freezers.xxxxx.Temperature_1] Value[null] Unit[Celsius]
2021-04-07 18:50:04.187  - debug: mielecloudservice.0 (12005) [createNumber]: invalid value detected. Skipping...
2021-04-07 18:50:04.190  - debug: mielecloudservice.0 (12005) createArray: Path:[Freezers.xxxx.Temperature_2]
2021-04-07 18:50:04.191  - debug:  mielecloudservice.0 (12005) createArray:   value:[[{"value_raw":-2000,"value_localized":-20,"unit":"Celsius"},{"value_raw":-32768,"value_localized":null,"unit":"Celsius"},{"value_raw":-32768,"value_localized":null,"unit":"Celsius"}]]
2021-04-07 18:50:04.191  - debug: mielecloudservice.0 (12005) createArray:  OrgUnit: [Celsius]
2021-04-07 18:50:04.191  - debug: mielecloudservice.0 (12005) [createNumber]: Path[Freezers.xxxx.Temperature_2] Value[null] Unit[Celsius]
2021-04-07 18:50:04.191  - debug: mielecloudservice.0 (12005) [createNumber]: invalid value detected. Skipping...
2021-04-07 18:50:04.192  - error:  mielecloudservice.0 (12005) [addMieleDeviceState]: Cannot read property  'toString' of null, Stacktrace: TypeError: Cannot read property  'toString' of null
at  Object.module.exports.createStateTargetTemperatureFreezer  (/opt/iobroker/node_modules/iobroker.mielecloudservice/miele-Tools.js:1402:128)
at addMieleDeviceState (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:558:34)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async addMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:337:17)
at async parseMieleDevice (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:297:5)
at async splitMieleDevices (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:273:9)
at async Timeout.schedule [as _onTimeout] (/opt/iobroker/node_modules/iobroker.mielecloudservice/main.js:653:21)

<img width="1151" alt="Bildschirmfoto 2021-04-07 um 18 47 41" src="https://user-images.githubusercontent.com/29131107/113904398-55013180-97d2-11eb-9c9d-8da8a51e52f9.png">
<img width="1250" alt="Bildschirmfoto 2021-04-07 um 18 47 17" src="https://user-images.githubusercontent.com/29131107/113904406-56caf500-97d2-11eb-9928-1b9181203f32.png">

**Comment by Grizzelbee** [comment]
### V4.0.5 (2021-04-08) (The haunting)
*  (grizzelbee) Fix: fixes ventilation step switch for hoods (attempt 2)
*  (grizzelbee) Fix: fixes error on creating TragetTemperature data points

**Comment by pacco81** [comment]
Hi !
Ich weiß du bekommst schon Alpträume, aber es klappt immer noch nicht:

Über die Katze bekomme ich nur die V.4.0.4.

Dort ist das Log jetzt fehlerfrei, aber die Targettemp wird als einzelnes Objekt bei einem Gerät ohne Nr. angelegt und funktioniert nicht.

<img width="1244" alt="Bildschirmfoto 2021-04-08 um 17 37 29" src="https://user-images.githubusercontent.com/29131107/114056149-a7555780-9891-11eb-9e45-b8775e0ca575.png">

**Comment by Grizzelbee** [comment]
Okay. da geht also noch etwas quer. ;)
Kannst Du mir bitte mal ein komplettes Debug-Log schicken? Vom Start des Adapters bis zum Ende (über Log-Herunterladen).

**Comment by pacco81** [comment]
Gerne ! 
[406.txt](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/6280752/406.txt)

**Comment by Grizzelbee** [comment]
### V4.0.7 (2021-04-09) (Lost in space)
*  (grizzelbee) Fix: [90](https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/90) added missing path to object ID; data point will be created in the correct place now
*  (grizzelbee) New: targetTemp min and max values are now taken from API - no constant values anymore

**Comment by pacco81** [comment]
Hi !

Du bist ja weiter dran. Vielen Dank. 
Leider bei 4.0.9 auch keine TargetTemp und folgende FehlerLog. volles Log anbei. 

P.S. Wenns dir hilft, kannst du dich auch gerne mit Teamviewer auf einen PC von mir aufschalten und basteln. Oder ich gebe dir per email die LogInDaten für Miele und du bindest die Gefriertruhe testweise in deinem iobroker ein.


<img width="1158" alt="Bildschirmfoto 2021-04-10 um 11 19 46" src="https://user-images.githubusercontent.com/29131107/114265035-d2a18900-99ee-11eb-9776-61582d2c1757.png">
<img width="1246" alt="Bildschirmfoto 2021-04-10 um 11 19 02" src="https://user-images.githubusercontent.com/29131107/114265036-d59c7980-99ee-11eb-8262-e198a3be2277.png">




[409.txt](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/6289570/409.txt)

**Comment by Grizzelbee** [comment]
Hi Pacco,

Danke für das Angebot. Teamviwer würde mangels Entwicklungsumgebung nichts helfen. Die Zugangsdaten natürlich schon.
Ich komme ggf. darauf zurück. Für den Moment recht aber tatsächlich das Log.
Da habe ich was mit den neu eingeführten Min-Max Werten vermurkst.
Hoffe das der Fix das behebt. Aber wir werden sehen. Ich habe noch Ausdauer. Es war ja zu erwarten, das bei der Umstrukturierung so einiges kaputt geht. Speziell in den Teilen, die ich nicht testen kann. Aber ich denke, das wir wirklich auf einem guten Weg sind.

### V4.0.10 (2021-04-10) (Another angel down)
*  (grizzelbee) Fix: targetTemp min and max values are now taken from API - no constant values anymore

**Comment by pacco81** [comment]
Hi !

TargetTemp mit 4010 klappt auch nicht: Log anbei.

Besten Dank !
[4010.txt](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/6290172/4010.txt)
<img width="794" alt="Bildschirmfoto 2021-04-10 um 17 38 20" src="https://user-images.githubusercontent.com/29131107/114275659-92a8c900-9a23-11eb-9ca7-e66d7f9bf94e.png">

**Comment by Grizzelbee** [comment]
Okay. manchmal hat man einfach mit der Adressierung von Variablen ein Brett vor dem Kopf oder stellt sich einfach nur blöd an.

Die 4.0.11 sollte es besser machen:
### V4.0.11 (2021-04-11) (Cry just a little)
*  (grizzelbee) Fix: targetTemp min and max values are now taken from API - no constant values anymore

**Comment by pacco81** [comment]
Hi ! 
Es geht vorwärts: Ich kann die targettemp jetzt versenden, wird aber nicht akzeptiert von der Cloud.
Wenn ich -22 oder '-22' verschicke kommt aber im Objekt "Action_Information( die Meldung "Please "Select a valid zone and temperature"

Ich weiß nicht was der erwartet als input. Hier steht dazu auch nix: https://www.miele.com/developer/swagger-ui/swagger.html. An anderer Stelle steht: 

zone | integer
value | integer

Im log finde ich dazu "targetTemperature":[{"zone":1,"min":-26,"max":-16}]

Wenn ich {1,-22} oder 1,-22 verschicke klappts auch nicht.

Wie kriege ich raus, was der haben will ?

[411.txt](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/6291900/411.txt)

**Comment by pacco81** [comment]
P.S. Laut Log schickt der Adapter  [{"targetTemperature":[{"zone":2,"value":-22}]}]

**Comment by Grizzelbee** [comment]
Das ist schon mal sehr gut! Wir sind auf dem Weg und kurz vor dem Ziel.
Das Problem gerade ist, das ich die Zonen aus Unwissenheit hast codiert hatte. Sprich: Zone 1 für Kühlschränke und 2 für Gefriergeräte. Das muss ich ketzt clso noch dynamisch machen.
Ich grübel mal, wie ich das hin bekomme ...

**Comment by pacco81** [comment]
Heureka !

Habe in meiner Installation in der Datei miele-api.tools einfach bei Freezer die Zone hart auf 1 geändert und jetzt klappt es.
Die Soll-Temp kommt binnen 2Sek. am Gefrierschrank an und wird so auch in der iOS-App angezeigt.
<img width="759" alt="Bildschirmfoto 2021-04-11 um 20 09 52" src="https://user-images.githubusercontent.com/29131107/114316466-fefaf980-9b03-11eb-8a7c-e45718c27d93.png">

Jetzt kann ich bei PV-Solarstromüberschuss neben der Wärmepumpe und  Klimaanlage auch den Gefrierschrank als PV-Speicher missbrauchen. 

**Tausend Dank !**

Reicht für die Zone nicht einfach eine manuelle Einstellung als Objekt ? Das automatische Abfragen der passenden Zone macht doch sicher mehr Arbeit, als einfach eine Variable vom User befüllen zu lassen.

P.S. Der Weg zurück scheint nocht nicht zu klappen: D.h. eine manuell geänderte Soll-Temp am Gerät oder iOS-App scheint nicht beim iobroker anzukommen, trotz Polling-Intervall von 1min. Aber das stört micht nicht.

**Comment by Grizzelbee** [comment]
Wir sind so weit gekommen, den Rest machen wir jetzt auch noch ordentlich. ;)  Zumal die Datei, die Du geändert hast, beim nächsten Update wieder übrschrieben wird und deine Änderung damit hinfällig ist. Es gibt also eigentlich keine Alternative zum "ordentlich machen". Aber es ist schon mal gut zu wissen, das das funktuioniert, wo wir hin wollen. Ich habe auch schon eine Idee dazu, muss aber noch schauen ob die aufgeht.
Das vom User setzen zu lassen würde ich aber nur ungern machen. woher soll der User denn wissen wo er Zone 1 und wo Zone 2 auswählen muss?

Das P.S. wundert mich sehr. Das sollte eigentlich seit eh und jeh funktionierten. Aber warten wir erst einmal ab. Ein Schritt nach dem anderen.

**Comment by Grizzelbee** [comment]
Vielleicht war die Lösung ja einfacher als gedacht: 😉 

### V4.0.12 (2021-04-12) (Promised land)
*  (grizzelbee) Fix: [90](https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/90) targetTemp addresses zones for fridges and freezers dynamically now

**Comment by pacco81** [comment]
Guten Morgen !
Mit 4011 klappts leider nicht.
Es wird als payload nur die Temp geschickt und jetzt gar keine Zone mehr.
Text Log kann ich heute Abend erst schicken.

Besten Dank !

![0DF3FDDF-85DD-46C3-894B-553C7E444661](https://user-images.githubusercontent.com/29131107/114353020-d824dd80-9b6c-11eb-88ef-d651299da56c.jpeg)

**Comment by Grizzelbee** [comment]
Hallo Sebastian,

die Idee die ich hatte (als solche) war gut, nur für die Durchführung war es heute morgen wohl noch etwas früh. Ich habe bei der Zuordnung zu den Aktionen (/Zonen) Kühl- und Gefriergeräte vertauscht. Ist in 4.0.13 gefixed.

### V4.0.13 (2021-04-12) (The toy master)
*  (grizzelbee) Fix: [90](https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/90) targetTemp addresses zones for fridges and freezers dynamically now

**Comment by pacco81** [comment]
Hi !
Jawoll, Jetzt klappts mit der 4013 !

Besten Dank nochmal !

**Comment by Grizzelbee** [comment]
Sehr gerne! 
Danke für deine Geduld und Hilfe!

**Comment by Grizzelbee** [comment]
Ach ja: Kannst Du bitte das hier
> P.S. Der Weg zurück scheint nocht nicht zu klappen: D.h. eine manuell geänderte Soll-Temp am Gerät oder iOS-App scheint nicht beim iobroker anzukommen, trotz Polling-Intervall von 1min. Aber das stört micht nicht.

noch einmal verifizieren und ggf. dafür einen Issue öffnen? Falls das tatsächlich kaputt ist, würde ich mir das schon gerne noch einmal angucken.
